location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_multirotor_simulator
    name: mrs_multirotor_simulator
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_multirotor_simulator
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_bumper.git
    name: mrs_bumper
    rev: hw_api_ci
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_bumper
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_state_estimators.git
    name: mrs_uav_state_estimators
    rev: hw_api_ci
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_state_estimators
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:ctu-mrs/mrs_uav_hw_api.git
    name: mrs_uav_hw_api
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_hw_api
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_lib.git
    name: mrs_lib
    rev: hw_api_ci
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_lib
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_msgs.git
    name: mrs_msgs
    rev: hw_api_ci
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    name: mrs_rviz_plugins
    rev: hw_api_ci
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: hw_api_ci
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_controllers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_general.git
    name: mrs_uav_general
    rev: hw_api_ci
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_general
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: hw_api_ci
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_managers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_status.git
    name: mrs_uav_status
    rev: hw_api_ci
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_status
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: hw_api_ci
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_testing
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: hw_api_ci
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_trackers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    name: mrs_uav_trajectory_generation
    rev: hw_api_ci
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_trajectory_generation
    scripts:
      - git submodule update --init --recursive
